dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - lts/*
  - node
script:
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: lts/*
      script: jest --coverage --coverageReporters=text-lcov | coveralls
    - stage: deploy
      if: branch = master && commit_message !~ /no-deploy/
      node_js: lts/*
      script: skip
      deploy:
        provider: npm
        email: litichevskiydv@gmail.com
        api_key:
          secure: N/0Dhs3s3QDtWZZTdMtVmTBM4KSvZEKeC+tEB/zJfD89y0gU6ecAamHrP8wO+y/j/NYkbZd6L/l9I2XtsCuk6yhCNJgPnRD5gBB/9oCU+Army3uDUw8SLy07vcB4o9gTfBnspCt5qUyz4X3gex9nSFa0cf58HR5vAjT7+i3Uz1w04U6lwhgJd/8ssFpTLogjQasIZFOtBCsieTgpkOhDH/qkiyrTUpGDsxP33ZLQpLvqBnDTCa4EN3BDJ7Jj5cJ4WrQ36TQ5QhTluGpLK0W1nAErxC/YwLLT0PSC1tGvGc2EnOZxVUBd5zIWvSHPEzrobTf3B2xIFfVFBufyJ8vtlkKwo3hwL9tce9D22aOuGHGCNI+VeNJiJ0lK7san+tZ/vrj13zlDDOrUFMYRl1EY9SIjO5P/IVxisS3uiBKHfdsL+d9wmfRLkWjNETmXH+CZzfxCTVSO/lF293mul57ahxDhj7uOVVFiUktOc83l8gzkFQCsIofQKp7UYZQrpUzGbNzzIGS2Dhyry3JZgMjMrjNdZo1oqKYTZx5w+m2ig3lQUG8zODT3kFFJW4MBOhPnnqnxVsOmDcbnx7OZS/kPA195tigoQE3Ox8iQZt4AUAqGGY4k7LJZidWnpi4AH5sY57xdF2pIZiABHw3shXEFQaha8u5omBnVVUvreJ8U8k4=
